### ISSUE TITLE
Add "Hot Edge" behavior

### ISSUE THREAD

**Issue by GaVenga** [acedron/auto-activities#10]
Auto-activities and hot edge make life easyer on Gnome40, but why two extensions?
If I have one App open, its difficult to start the next one; I use Dash to Panel too,
and the choice for next app  is to click on the nine-point icon exor use windows-key.

**Comment by acedron** [comment]
I get that it would be good to have fewer extensions do the same thing, but Auto Activities is a simple extension and I want to keep it so. I don't want to mix many features that aren't related to the main topic, which is showing the overview when there are no visible windows. I'm sorry.

**Comment by acedron** [comment]
Dash to Panel's GNOME 40 support hasn't been released yet, so it is expected to see some incompatibilities. I will still take a look at the issue in a fresh GNOME OS installation though. However, I couldn't get what you tried to say in the bottom paragraph. I think it might be related to Dash to Panel too.

**Comment by GaVenga** [comment]
> I think it might be related to Dash to Panel too.
Yes. Latest version of DtP doesnot do such nonsense,  ;- ))
you are definitly innocent.
